
version: "3.8"
services:
  php-apache-environment:
    container_name: Week6_php
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: DB_Week6
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB6
      MYSQL_DATABASE: MY_DATABASE
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: DB6
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3000:80"
    restart: always
    environment:
      PMA_HOST: DB_Week6
    depends_on:
      - db
    
