version: "3.8"
services:
  php-apache-environment:
    container_name: midterm_php
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8081:80