version: "3.8"
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: ./src
      dockerfile: Dockerfile
    depends_on:
      - db
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  db:
    container_name: Db_php
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: My_DB-lek
      MYSQL_USER: MYSQL_USER
      MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "3000:80"
    restart: always
    environment:
      PMA_HOST: Db_php
    depends_on:
      - db
    
